#!/bin/bash
# Array of subfolder names
internalFolder=(
	'homework'
	'instructor_notes'
	'instructor_examples'
	'morning_exercise'
	'student_labs'
	'student_examples'
)
# The count is for the index of the internalFolder array
count=0

# The number of the first unit in your program
unit=1

# Adding .gitkeep to empty folders
find . -type d -empty -not -path "./.git/*" -exec touch {}/.gitkeep \;

# Creating a README file in the root directory with the GA logo
echo "![ga](http://mobbook.generalassemb.ly/ga_cog.png) <br> ## Licensing <br> 1. All content is licensed under a CC­BY­NC­SA 4.0 license.<br> 1. All software code is licensed under GNU GPLv3. For commercial use or alternative licensing, please contact legal@ga.co." >> README.md

# Creating a LICENSE file in the root directory - this will need to be completed by the individual cohort
echo "Please fill this out with the License information found on Confluence" >> LICENSE.txt

# Creating a Project folder with Projects 1-4 and `final_project` as subfolders
mkdir projects
mkdir projects/project_{1..4}
mkdir projects/final_projects

# Loop to write unit 1 folders and subfolders
while [ $unit -eq 1 ]; do
	mkdir unit_$unit
	mkdir unit_$unit/w{01..04}d{01..05}
		for i in "${internalFolder[@]}"
			do
			mkdir unit_$unit/w{01..04}d{01..05}/$i
			find . -type d -empty -not -path "./.git/*" -exec touch {}/.gitkeep \;
		done
	let unit=unit+1
done

# Loop to write unit 2 folders and subfolders
while [ $unit -eq 2 ]; do
	mkdir unit_$unit
	mkdir unit_$unit/w{05..07}d{01..05}
		for i in "${internalFolder[@]}"
			do
			mkdir unit_$unit/w{05..07}d{01..05}/$i
			find . -type d -empty -not -path "./.git/*" -exec touch {}/.gitkeep \;
		done
	let unit=unit+1
done

# Loop to write unit 3 folders and subfolders
while [ $unit -eq 3 ]; do
	mkdir unit_$unit
	mkdir unit_$unit/w{08..09}d{01..05}
		for i in "${internalFolder[@]}"
			do
			mkdir unit_$unit/w{08..09}d{01..05}/$i
			find . -type d -empty -not -path "./.git/*" -exec touch {}/.gitkeep \;
		done
	let unit=unit+1
done

# Loop to write unit 4 folders and subfolders
while [ $unit -eq 4 ]; do
	mkdir unit_$unit
	mkdir unit_$unit/w{10..11}d{01..05}
		for i in "${internalFolder[@]}"
			do
			mkdir unit_$unit/w{10..11}d{01..05}/$i
			find . -type d -empty -not -path "./.git/*" -exec touch {}/.gitkeep \;
		done
	let unit=unit+1
done

# Loop to write unit 5 folders and subfolders
while [ $unit -eq 5 ]; do
	mkdir unit_$unit
	mkdir unit_$unit/w{12..13}d{01..05}
		for i in "${internalFolder[@]}"
			do
			mkdir unit_$unit/w{12..13}d{01..05}/$i
			find . -type d -empty -not -path "./.git/*" -exec touch {}/.gitkeep \;
		done
	let unit=unit+1
done
